CREATE OR REPLACE VIEW CAPSTONE_DE.GROUP_3_SCHEMA.AVG_TAXI_STATS_VIEW(
    BOROUGH,
    AVG_PASSENGER_COUNT,
    AVG_TRIP_DISTANCE,
    AVG_RIDE_COUNT,
    AVG_FARE_AMOUNT,
    AVG_TIP_AMOUNT,
    AVG_TOTAL_AMOUNT
) AS
SELECT  BOROUGH,
        ROUND(AVG(PASSENGER_COUNT), 1) AS AVG_PASSENGER_COUNT,
        ROUND(AVG(TRIP_DISTANCE), 2) AS AVG_TRIP_DISTANCE,
        ROUND(SUM(vendorid), 2) AS AVG_RIDE_COUNT,
        ROUND(AVG(FARE_AMOUNT), 2) AS AVG_FARE_AMOUNT,
        ROUND(AVG(TIP_AMOUNT), 2) AS AVG_TIP_AMOUNT,
        ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_TOTAL_AMOUNT
FROM FACT_GREEN_YELLOW F
JOIN DIM_ZONE_LOOKUP Z ON F.PULOCATIONID = Z.LOCATIONID
WHERE BOROUGH IN ('Bronx', 'Brooklyn', 'Queens', 'Staten Island', 'Manhattan')
GROUP BY BOROUGH
ORDER BY AVG_RIDE_COUNT;
