CREATE VIEW capstone_de.group_3_schema.PICKUPS_BOROUGH_ZONE_VW AS
SELECT BOROUGH, ZONE, COUNT(PULOCATIONID) as NUM_OF_PICKUPS
FROM FACT_GREEN_YELLOW as f
JOIN dim_zone_lookup as l ON f.PULOCATIONID = l.LOCATIONID
GROUP BY l.borough, l.zone
ORDER BY NUM_OF_PICKUPS DESC;
