CREATE OR REPLACE VIEW CAPSTONE_DE.GROUP_3_SCHEMA.PRICE_HR_VIEW (
    HOUR_OF_DAY,
    TIME_OF_DAY,
    DAY_OF_WEEK,
    RIDE_COUNT,
    BOROUGH
) AS
SELECT HOUR, TIMEOFDAY, DAY_OF_WEEK, SUM(VENDORID) AS RIDE_COUNT, BOROUGH
FROM FACT_GREEN_YELLOW F
JOIN DIM_ZONE_LOOKUP Z ON F.PULOCATIONID = Z.LOCATIONID
WHERE BOROUGH IN ('Bronx', 'Brooklyn', 'Queens', 'Staten Island', 'Manhattan')
GROUP BY HOUR, TIMEOFDAY, DAY_OF_WEEK, BOROUGH
ORDER BY RIDE_COUNT DESC;
